apiVersion: v1
kind: Template
metadata:
  name: topological-inventory-ingress-api
objects:
- apiVersion: v1
  kind: Secret # For ephemeral/local environment
  metadata:
    name: topological-inventory-api-secrets
    labels:
      app: topological-inventory
  stringData:
    encryption-key: "${ENCRYPTION_KEY}"
    secret-key: "${SECRET_KEY}"
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: topo-ingress-api
    labels:
      app: topological-inventory
      clowdapp: topo-ingress-api
  spec:
    envName: ${ENV_NAME}
    deployments:
    - name: svc
      minReplicas: ${{MIN_REPLICAS}}
      webServices:
        public:
          enabled: true # port 8000 is default in ClowdEnvironment
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        env:
        - name: RAILS_LOG_LEVEL
          value: ${LOG_LEVEL}
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: topological-inventory-api-secrets
              key: secret-key
        readinessProbe:
          tcpSocket:
            port: 8000
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 120
        resources:
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
          requests:
            cpu: ${CPU_REQUEST}
            memory: ${MEMORY_REQUEST}
    kafkaTopics:
    - topicName: platform.topological-inventory.persister # producer
      partitions: 3
      replicas: 3
- apiVersion: v1
  kind: Service
  metadata:
    name: topo-ingress-api-transitional
    labels:
      app: topo-ingress-api
      pod: topo-ingress-api-svc
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8000
      name: weblegacy
    selector:
      pod: topo-ingress-api-svc
parameters:
- name: CPU_LIMIT
  value: 200m
- name: CPU_REQUEST
  value: 100m
- description: Clowder ENV
  name: ENV_NAME
  required: true
- description: Image
  name: IMAGE
  value: quay.io/cloudservices/topological-inventory-ingress-api
- description: Image tag
  name: IMAGE_TAG
  required: true
- name: LOG_LEVEL
  value: WARN
- name: MEMORY_LIMIT
  value: 1Gi
- name: MEMORY_REQUEST
  value: 500Mi
- description: The number of replicas to use for the prometheus deployment
  name: MIN_REPLICAS
  value: '1'
